[package]
name = "file_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir   = "2"
ignore    = "0.4"
sha2      = "0.10"
hex       = "0.4"
rayon     = "1.10"
mime_guess = "2"
base64    = "0.22"
serde     = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time      = { version = "0.3", features = ["serde-human-readable"] }
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.22"
